config/routes.rb
Rails.application.routes.draw do

  resources :jobs

  resources :categories

  get '/login' => 'pages#home'
  post '/login' => 'sessions#create', as: :log_in
  get '/logout' => 'sessions#destroy', as: :log_out

  get 'users/newpass/:id', to: 'users#new_pass', as: :new_pass

  get '/employer/home', to: 'jobs#index', as: :employer_home
  get '/jobseeker/home', to: 'jobseekers#index', as: :jobseeker_home

  post '/jobseeker/home', to: 'jobseekers#create_application', as: :jobapplications
  get '/jobseeker/applications', to: 'jobseekers#view_applications', as: :view_applications
  get '/jobseeker/application/:id', to: 'jobseekers#view_application', as: :view_application

  get '/jobs/applications/:id', to: 'jobs#view_applications', as: :view_applications_employer

  get 'job/changestatus/:id', to: 'jobs#change_status', as: :change_status
  patch 'job/changestatus/:id', to: 'jobs#update_status', as: :jobapplication

  patch 'users/newpass/:id', to: 'users#update_password', as: :pass_update

  get 'pages/home'
  get 'preview', to: 'pages#preview', as: :preview_jobs

  get 'jobs/view/:id', to: 'jobseekers#view_job', as: :view_job
  get 'jobs/apply/:id', to: 'jobseekers#apply_job', as: :apply_job

  get 'jobseekers/:id', to: 'users#view_jobseeker', as: :view_jobseeker
  delete 'jobseekers/:id', to: 'users#destroy_jobseeker', as: :destroy_jobseeker

  get 'employer/view', to: 'jobs#view_employer_profile', as: :employer_profile
  get 'employer/edit', to: 'jobs#edit_employer_profile', as: :edit_employer_profile
  get 'employer/newpass', to: 'jobs#new_employer_pass', as: :new_employer_pass

  match 'employer/password/update', to: 'jobs#update_employer_password', via: [:patch, :put], as: :update_employer_password
  match 'employer/update', to: 'jobs#update_employer_profile', via: [:patch, :put], as: :update_employer_profile

  get 'jobseeker/view', to: 'jobseekers#view_jobseeker_profile', as: :jobseeker_profile
  get 'jobseeker/edit', to: 'jobseekers#edit_jobseeker_profile', as: :edit_jobseeker_profile
  get 'jobseeker/newpass', to: 'jobseekers#new_jobseeker_pass', as: :new_jobseeker_pass

  match 'jobseeker/password/update', to: 'jobseekers#update_jobseeker_password', via: [:patch, :put], as: :update_jobseeker_password
  match 'jobseeker/update', to: 'jobseekers#update_jobseeker_profile', via: [:patch, :put], as: :update_jobseeker_profile

  get 'jobseeker/create', to: 'jobseekers#new', as: :create_new_jobseeker
  get 'jobseeker/recommendations', to: 'jobseekers#recommendations', as: :recommendations
  get 'jobseeker/recommendations/consolidated', to: 'jobseekers#consolidated_recommendations', as: :consolidated_recommendations

  get '/search', to: 'pages#search', as: :search

  resources :users
  resources :admins, controller: 'users'
  resources :employers
  resources :jobseekers

  root 'pages#home'

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessor :tags
  belongs_to :employer
  belongs_to :category
  has_many :jobapplications, dependent: :destroy
  has_many :tags, dependent: :destroy

  #before_save :add_tags, :if => :tags

  def get_tags
    self.tags.split(',')
  end

  def self.search(q,titles,desc,emp,cat,tags)
    jobs = []
    if q
      #find(:all, :conditions => ['name LIKE ?', "%#{q}%"])
      if titles
        jobs.concat Job.where('title like ?',"%#{q}%")
      end
      if desc
        jobs.concat Job.where('description like ?',"%#{q}%")
      end
      if emp
        jobs.concat Job.where(employer_id: Employer.where('name like ?',"%#{q}%"))
      end
      if cat
        jobs.concat Job.where(category_id: Category.where('name like ?',"%#{q}%"))
      end
      if tags
        jobs.concat Job.where(id: Tag.where('name like ?',"%#{q}%").map{|x| x.job_id})
      end
      jobs.uniq!
      jobs
    else
      jobs.concat Job.all
      jobs
    end
  end

  def self.recommendations(user)
    apps = Jobapplication.where(jobseeker_id: user)
    job_ids = apps.map {|x| x.job_id}
    jobs_applied = Job.where(id: job_ids)

    tags = (Tag.where(job_id: jobs_applied).map{|x| x.name}).uniq
    tag_recos = Job.where(id: Tag.where(name: tags).map{|x| x.job_id}.uniq)

    categories = Category.where(id: jobs_applied.map{|x| x.category_id}.uniq)
    cat_recos = Job.where(category_id: categories)

    employers = Employer.where(id: jobs_applied.map{|x| x.employer_id}.uniq)
    emp_recos = Job.where(employer_id: employers)

    return tag_recos, cat_recos, emp_recos
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  before_action :check_if_employer
  before_action :job_check_for_id_job, only: [:show, :edit, :update, :destroy, :view_applications]
  before_action :job_check_for_id_application, only: [:change_status, :update_status]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.where(employer_id: session[:user_id])
    @category = Category.all
    @tags = Tag.all
    @employer = Employer.find(session[:user_id]).name
    @this_user = Employer.find(session[:user_id])
    @applications = Jobapplication.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @category = Category.find(@job.category_id).name
    @employer = Employer.find(@job.employer_id).name
    tags_list = Tag.where(job_id: @job.id)
    @tags = ""
    tags_list.each do |tag|
      @tags += " " + tag.name.strip
    end
    @applications = Jobapplication.where(job_id: @job.id).count
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @category = Category.all
    @employer_id = session[:user_id]
    @employer_name = Employer.find(@employer_id).name
  end

  # GET /jobs/1/edit
  def edit
    @category = Category.all
    @employer_id = session[:user_id]
    @employer_name = Employer.find(@employer_id).name
    tags_list = Tag.where(job_id: @job.id)
    tag_names = []
    tags_list.each do |tag|
      tag_names = tag_names << tag.name.strip
    end
    @tags = tag_names.join(",")
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if @job.save
        tag_array = @job.get_tags
        tag_array.each do |a|
          tag = Tag.new
          tag.name = a.strip
          tag.job_id = @job.id
          tag.save
        end
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        tags_list = Tag.where(job_id: @job.id)
        tags_list.each do |tag|
          tag.destroy
        end

        tag_array = @job.get_tags
        tag_array.each do |a|
          tag = Tag.new
          tag.name = a.strip
          tag.job_id = @job.id
          tag.save
        end
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    @application = Jobapplication.find(params[:id])
    @job = Job.find(@application.job_id)
    @employer = Employer.find(@job.employer_id)
    @jobseeker = Jobseeker.find(@application.jobseeker_id)
    respond_to do |format|
      if @application.update(update_status_params)

        UserMailer.application_status_update(@job,@employer,@jobseeker).deliver

        format.html { redirect_to view_applications_employer_path(@job), notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :change_status }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def view_applications
    @job = Job.find(params[:id])
    @applications = Jobapplication.where(job_id: @job.id)
    @jobseekers = Jobseeker.all
  end

  def change_status
    @application = Jobapplication.find(params[:id])
    @job_status = @application.status
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def view_employer_profile
    @title = 'My Profile'
    @employer = Employer.find(session[:user_id])
  end

  def edit_employer_profile
    @title = 'Edit Profile'
    @employer = Employer.find(session[:user_id])
  end

  def update_employer_profile
    @employer = Employer.find(session[:user_id])
    respond_to do |format|
      if @employer.update(employer_update_params)
        format.html { redirect_to employer_profile_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit_employer_profile }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_employer_pass
    @title = 'Change Password'
    @user = User.find(session[:user_id])
  end

  def update_employer_password
    @user = Employer.find(session[:user_id])
    respond_to do |format|
      if @user.update(employer_password_params)
        format.html { redirect_to employer_profile_path, notice: 'Password was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :new_employer_pass }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :employer_id, :category_id, :deadline, :tags)
    end

    def employer_update_params
      params.require(:employer).permit(:name, :email, :username, :phone, :type, :contact_name)
    end

    def update_status_params
      params.require(:jobapplication).permit(:status)
    end

    def employer_password_params
      params.require(:employer).permit(:password_hash, :password_salt, :password, :password_confirmation, :type)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employer_id, "Employer: #{@employer_name}" %><br>
    <%= f.hidden_field :employer_id, value: @employer_id %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category_id, "Category" %><br>
    <%= f.select :category_id, options_for_select(@category.map{ |s| [s.name, s.id] }) %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :tags, "Tags: (Enter multiple tags separated by commas)" %><br>
    <%= f.text_area :tags, value: @tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_show_job.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @employer %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @job.deadline %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @tags %>
</p>

<p>
  <strong>No. of applications:</strong>
  <%= @applications %>
</p>

app/views/jobs/change_status.html.erb
<h1>Update Job Status:</h1>

<%= form_for(@application) do |f| %>
    <% if @application.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@application.errors.count, "error") %> prohibited this job from being saved:</h2>

          <ul>
            <% @application.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :status, "Select status:" %><br>
      <%= f.select :status,
          options_for_select([["Pending","Pending"],["Not a fit","Not a fit"],["Schedule Interview","Schedule Interview"]],@job_status)
      %>
      <br><br>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>

<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Back', @job %>

app/views/jobs/edit_employer_profile.html.erb
<h1>Editing profile</h1>

<%= form_for(@employer, as: :employer, url: update_employer_profile_path) do |f| %>
    <% if @employer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @employer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name, "Company Name" %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :contact_name, "Employer POC name" %><br>
      <%= f.text_field :contact_name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<br><%= link_to 'Change Password', new_employer_pass_path %><br>
<%= link_to 'Back', employer_profile_path %>

app/views/jobs/index.html.erb
<h1>Hello, <%= @this_user.name.titleize %>!</h1>
<h2>My jobs</h2>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Employer</th>
      <th>Category</th>
      <th>Deadline</th>
      <th>Applications</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= @employer %></td>
        <td><%= @category.find(job.category_id).name %></td>
        <td><%= job.deadline %></td>
        <td style="text-align:center">
          <% apps = @applications.where(job_id: job.id) %>
          <%= apps.count %>
          <% if apps %>
            <% apps.each do |app|%>
                <% app %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %> |
<%= link_to 'My Profile', employer_profile_path %><br>
<%= link_to 'Log out', log_out_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/new_employer_pass.html.erb
<h1>Change Password</h1>

<%= form_for(@user, as: :employer, url: update_employer_password_path) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :password, "Enter new password" %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirm password" %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<br>
<%= link_to 'Back', edit_employer_profile_path %>

app/views/jobs/show.html.erb
<%= render "jobs/show_job" %>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'View Applications', view_applications_employer_path(@job) %> |
<%= link_to 'Back', employer_home_path %>

app/views/jobs/view_applications.html.erb
<h2>Your Job applications:</h2>

<table>
  <thead>
  <tr>
    <th>Applicant Name</th>
    <th>Application Date</th>
    <th>Resume</th>
    <th>Cover Letter</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @applications.each do |application| %>
      <tr>
        <% job_seeker = @jobseekers.find(application.jobseeker_id) %>
        <td><%= job_seeker.name %></td>
        <td><%= application.application_date %></td>
        <td><%= job_seeker.resume %></td>
        <td><%= application.cover_letter %></td>
        <td><%= application.status %></td>
        <td><%= link_to 'Update status', change_status_path(application) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>


<br>
<%= link_to 'Back', employer_home_path %>&nbsp;

app/views/jobs/view_employer_profile.html.erb
<h1>My Profile</h1>

<p>
  <strong>Name:</strong>
  <%= @employer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employer.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @employer.username %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employer.phone %>
</p>

<p>
  <strong>Contact person name:</strong>
  <%= @employer.contact_name %>
</p>

<%= link_to 'Edit', edit_employer_profile_path %> |
<%= link_to 'Back', employer_home_path %>