config/routes.rb
Rails.application.routes.draw do

  resources :jobs

  resources :categories

  get '/login' => 'pages#home'
  post '/login' => 'sessions#create', as: :log_in
  get '/logout' => 'sessions#destroy', as: :log_out

  get 'users/newpass/:id', to: 'users#new_pass', as: :new_pass

  get '/employer/home', to: 'jobs#index', as: :employer_home
  get '/jobseeker/home', to: 'jobseekers#index', as: :jobseeker_home

  post '/jobseeker/home', to: 'jobseekers#create_application', as: :jobapplications
  get '/jobseeker/applications', to: 'jobseekers#view_applications', as: :view_applications
  get '/jobseeker/application/:id', to: 'jobseekers#view_application', as: :view_application

  get '/jobs/applications/:id', to: 'jobs#view_applications', as: :view_applications_employer

  get 'job/changestatus/:id', to: 'jobs#change_status', as: :change_status
  patch 'job/changestatus/:id', to: 'jobs#update_status', as: :jobapplication

  patch 'users/newpass/:id', to: 'users#update_password', as: :pass_update

  get 'pages/home'
  get 'preview', to: 'pages#preview', as: :preview_jobs

  get 'jobs/view/:id', to: 'jobseekers#view_job', as: :view_job
  get 'jobs/apply/:id', to: 'jobseekers#apply_job', as: :apply_job

  get 'jobseekers/:id', to: 'users#view_jobseeker', as: :view_jobseeker
  delete 'jobseekers/:id', to: 'users#destroy_jobseeker', as: :destroy_jobseeker

  get 'employer/view', to: 'jobs#view_employer_profile', as: :employer_profile
  get 'employer/edit', to: 'jobs#edit_employer_profile', as: :edit_employer_profile
  get 'employer/newpass', to: 'jobs#new_employer_pass', as: :new_employer_pass

  match 'employer/password/update', to: 'jobs#update_employer_password', via: [:patch, :put], as: :update_employer_password
  match 'employer/update', to: 'jobs#update_employer_profile', via: [:patch, :put], as: :update_employer_profile

  get 'jobseeker/view', to: 'jobseekers#view_jobseeker_profile', as: :jobseeker_profile
  get 'jobseeker/edit', to: 'jobseekers#edit_jobseeker_profile', as: :edit_jobseeker_profile
  get 'jobseeker/newpass', to: 'jobseekers#new_jobseeker_pass', as: :new_jobseeker_pass

  match 'jobseeker/password/update', to: 'jobseekers#update_jobseeker_password', via: [:patch, :put], as: :update_jobseeker_password
  match 'jobseeker/update', to: 'jobseekers#update_jobseeker_profile', via: [:patch, :put], as: :update_jobseeker_profile

  get 'jobseeker/create', to: 'jobseekers#new', as: :create_new_jobseeker
  get 'jobseeker/recommendations', to: 'jobseekers#recommendations', as: :recommendations
  get 'jobseeker/recommendations/consolidated', to: 'jobseekers#consolidated_recommendations', as: :consolidated_recommendations

  get '/search', to: 'pages#search', as: :search

  resources :users
  resources :admins, controller: 'users'
  resources :employers
  resources :jobseekers

  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password, :password_confirmation

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user && user.password_hash == user.encrypt(password)
      user
    else
      nil
    end
  end

  def encrypt_password
    self.password_salt = make_salt unless self.password_salt
    self.password_hash = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{self.password_salt}_-_#{string}")
  end

  private

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

  def make_salt
    require 'securerandom'
    SecureRandom.hex
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  before_action :check_if_admin

  # GET /users
  # GET /users.json
  def index
    @title = 'Home'
    @this_user = Admin.find(session[:user_id])
    @users = User.all
    @categories = Category.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @title = 'View User'
  end

  # GET /users/new
  def new
    @title = 'New'
    @user = Admin.new
  end

  # GET /users/1/edit
  def edit
    @title = 'Edit User'
  end

  # POST /users
  # POST /users.json
  def create
    @user = Admin.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if (@user.username == "super")
      redirect_home
    else
      respond_to do |format|
        if @user.update(user_params_update)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update_password
    @user = User.find(params[:id])
    if (@user.username == "super")
      redirect_home
    else
      respond_to do |format|
        if @user.update(user_params_update_password)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :new_pass }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if (@user.username == "super")
      redirect_home
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully removed.' }
        format.json { head :no_content }
      end
    end
  end

  def destroy_jobseeker
    @user = Jobseeker.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def new_pass
    @title = 'Change Password'
    @user = User.find(params[:id])
  end

  def view_jobseeker
    @title = 'View Job Seeker'
    @job_seeker = Jobseeker.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = Admin.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:admin).permit(:name, :email, :username, :password_hash, :password, :password_confirmation, :password_salt, :phone, :type)
    end

  def user_params_update
    params.require(:admin).permit(:name, :email, :username, :phone, :type)
  end

  def user_params_update_password
    if(params[:admin])
      params.require(:admin).permit(:password, :password_confirmation)
    elsif(params[:employer])
      params.require(:employer).permit(:password, :password_confirmation)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<br><%= link_to 'Change Password', new_pass_path(@user.id) %><br>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Hello, <%= @this_user.name.titleize %>!</h1>
<h2>Existing users:</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Phone</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if user.type == 'Admin' then %>
          <% edit_path = edit_user_path(user) %>
      <% elsif user.type == 'Employer' %>
          <% edit_path = edit_employer_path(user) %>
      <% end %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.phone %></td>
        <td><%= user.type %></td>
        <td><%= link_to 'View', user %></td>
        <td>
          <% unless(user.username == "super") %>
            <%= link_to 'Remove', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Existing Categories:</h2>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'View', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
Create: <%= link_to 'New Admin', new_user_path %>&nbsp;
<%= link_to 'New Employer', new_employer_path %>&nbsp;
<%= link_to 'New Category', new_category_path %><br>
<%= link_to 'My Profile', user_path(@this_user.id) %><br>
<%= link_to 'Log out', log_out_path %>

app/views/users/new.html.erb
<h1>New Admin user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new_pass.html.erb
<h1>Change Password</h1>

<%= form_for(@user, url: pass_update_path) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :password, "Enter new password" %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirm password" %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<br>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Type:</strong>
  <%= @user.type %>
</p>

<% unless(@user.username == "super") %>
    <%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', users_path %>

app/views/users/view_jobseeker.html.erb
<p>
  <strong>Name:</strong>
  <%= @job_seeker.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @job_seeker.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @job_seeker.username %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @job_seeker.skills %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @job_seeker.resume %>
</p>

<p>
  <strong>Type:</strong>
  <%= @job_seeker.type %>
</p>

<%= link_to 'Back', users_path %>