config/routes.rb
Rails.application.routes.draw do

  resources :jobs

  resources :categories

  get '/login' => 'pages#home'
  post '/login' => 'sessions#create', as: :log_in
  get '/logout' => 'sessions#destroy', as: :log_out

  get 'users/newpass/:id', to: 'users#new_pass', as: :new_pass

  get '/employer/home', to: 'jobs#index', as: :employer_home
  get '/jobseeker/home', to: 'jobseekers#index', as: :jobseeker_home

  post '/jobseeker/home', to: 'jobseekers#create_application', as: :jobapplications
  get '/jobseeker/applications', to: 'jobseekers#view_applications', as: :view_applications
  get '/jobseeker/application/:id', to: 'jobseekers#view_application', as: :view_application

  get '/jobs/applications/:id', to: 'jobs#view_applications', as: :view_applications_employer

  get 'job/changestatus/:id', to: 'jobs#change_status', as: :change_status
  patch 'job/changestatus/:id', to: 'jobs#update_status', as: :jobapplication

  patch 'users/newpass/:id', to: 'users#update_password', as: :pass_update

  get 'pages/home'
  get 'preview', to: 'pages#preview', as: :preview_jobs

  get 'jobs/view/:id', to: 'jobseekers#view_job', as: :view_job
  get 'jobs/apply/:id', to: 'jobseekers#apply_job', as: :apply_job

  get 'jobseekers/:id', to: 'users#view_jobseeker', as: :view_jobseeker
  delete 'jobseekers/:id', to: 'users#destroy_jobseeker', as: :destroy_jobseeker

  get 'employer/view', to: 'jobs#view_employer_profile', as: :employer_profile
  get 'employer/edit', to: 'jobs#edit_employer_profile', as: :edit_employer_profile
  get 'employer/newpass', to: 'jobs#new_employer_pass', as: :new_employer_pass

  match 'employer/password/update', to: 'jobs#update_employer_password', via: [:patch, :put], as: :update_employer_password
  match 'employer/update', to: 'jobs#update_employer_profile', via: [:patch, :put], as: :update_employer_profile

  get 'jobseeker/view', to: 'jobseekers#view_jobseeker_profile', as: :jobseeker_profile
  get 'jobseeker/edit', to: 'jobseekers#edit_jobseeker_profile', as: :edit_jobseeker_profile
  get 'jobseeker/newpass', to: 'jobseekers#new_jobseeker_pass', as: :new_jobseeker_pass

  match 'jobseeker/password/update', to: 'jobseekers#update_jobseeker_password', via: [:patch, :put], as: :update_jobseeker_password
  match 'jobseeker/update', to: 'jobseekers#update_jobseeker_profile', via: [:patch, :put], as: :update_jobseeker_profile

  get 'jobseeker/create', to: 'jobseekers#new', as: :create_new_jobseeker
  get 'jobseeker/recommendations', to: 'jobseekers#recommendations', as: :recommendations
  get 'jobseeker/recommendations/consolidated', to: 'jobseekers#consolidated_recommendations', as: :consolidated_recommendations

  get '/search', to: 'pages#search', as: :search

  resources :users
  resources :admins, controller: 'users'
  resources :employers
  resources :jobseekers

  root 'pages#home'

end

app/views/pages/_search_form.html.erb
<%= form_tag("/search", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q, @search_string, select_all: true) %>
    <% select_tag :search_type,
                  options_for_select(["Job Titles","Job Description","Employer","Tags"],["Employer","Tags"]),
                  multiple: true
    %>

    <%= check_box_tag(:titles, 1, @titles_true) %>
    <%= label_tag(:titles, "Job Titles") %>
    <%= check_box_tag(:desc, 1, @desc_true) %>
    <%= label_tag(:desc, "Job Descriptions") %>
    <%= check_box_tag(:emp, 1, @emp_true) %>
    <%= label_tag(:emp, "Employers") %>
    <%= check_box_tag(:cat, 1, @cat_true) %>
    <%= label_tag(:cat, "Category") %>
    <%= check_box_tag(:tags, 1, @tags_true) %>
    <%= label_tag(:tags, "Tags") %>
    <%= submit_tag("Search") %>

<% end %><br>

app/views/pages/home.html.erb
<h1>DireWolf Home</h1>

<br>
<h2>Log In</h2>

<%=form_tag log_in_path do%>
    <%=label_tag :username %>
    <%=text_field_tag :username %>
    <br><br>
    <%=label_tag :password %>
    <%=password_field_tag :password %>
    <br><br>
    <%=submit_tag "Log in" %>
<%end%>

<br>

<%= link_to "Looking for jobs? Sign up here!", create_new_jobseeker_path  %> |
<%= link_to "Preview Jobs", preview_jobs_path  %>

app/views/pages/preview.html.erb
<h2>Previewing Available Jobs:</h2>

<%= render 'pages/search_form' %>

<%= render 'jobseekers/jobs_table' %>

<br>


<br>
<%= link_to 'Back', pages_home_path %>&nbsp;

app/views/pages/search.html.erb
<h1>Search Results for: <%= @search_string %></h1>

<%= render 'search_form' %>

<%= render 'jobseekers/jobs_table' %>

<br>
<% if session[:user_id] %>
    <% if(Jobseeker.find(session[:user_id])) %>
        <% back = jobseeker_home_path %>
    <% else %>
        <% back = pages_home_path %>
    <% end %>
<% else %>
    <% back = pages_home_path %>
<% end %>

<%= link_to 'Back', back %>