config/routes.rb
Rails.application.routes.draw do

  resources :jobs

  resources :categories

  get '/login' => 'pages#home'
  post '/login' => 'sessions#create', as: :log_in
  get '/logout' => 'sessions#destroy', as: :log_out

  get 'users/newpass/:id', to: 'users#new_pass', as: :new_pass

  get '/employer/home', to: 'jobs#index', as: :employer_home
  get '/jobseeker/home', to: 'jobseekers#index', as: :jobseeker_home

  post '/jobseeker/home', to: 'jobseekers#create_application', as: :jobapplications
  get '/jobseeker/applications', to: 'jobseekers#view_applications', as: :view_applications
  get '/jobseeker/application/:id', to: 'jobseekers#view_application', as: :view_application

  get '/jobs/applications/:id', to: 'jobs#view_applications', as: :view_applications_employer

  get 'job/changestatus/:id', to: 'jobs#change_status', as: :change_status
  patch 'job/changestatus/:id', to: 'jobs#update_status', as: :jobapplication

  patch 'users/newpass/:id', to: 'users#update_password', as: :pass_update

  get 'pages/home'
  get 'preview', to: 'pages#preview', as: :preview_jobs

  get 'jobs/view/:id', to: 'jobseekers#view_job', as: :view_job
  get 'jobs/apply/:id', to: 'jobseekers#apply_job', as: :apply_job

  get 'jobseekers/:id', to: 'users#view_jobseeker', as: :view_jobseeker
  delete 'jobseekers/:id', to: 'users#destroy_jobseeker', as: :destroy_jobseeker

  get 'employer/view', to: 'jobs#view_employer_profile', as: :employer_profile
  get 'employer/edit', to: 'jobs#edit_employer_profile', as: :edit_employer_profile
  get 'employer/newpass', to: 'jobs#new_employer_pass', as: :new_employer_pass

  match 'employer/password/update', to: 'jobs#update_employer_password', via: [:patch, :put], as: :update_employer_password
  match 'employer/update', to: 'jobs#update_employer_profile', via: [:patch, :put], as: :update_employer_profile

  get 'jobseeker/view', to: 'jobseekers#view_jobseeker_profile', as: :jobseeker_profile
  get 'jobseeker/edit', to: 'jobseekers#edit_jobseeker_profile', as: :edit_jobseeker_profile
  get 'jobseeker/newpass', to: 'jobseekers#new_jobseeker_pass', as: :new_jobseeker_pass

  match 'jobseeker/password/update', to: 'jobseekers#update_jobseeker_password', via: [:patch, :put], as: :update_jobseeker_password
  match 'jobseeker/update', to: 'jobseekers#update_jobseeker_profile', via: [:patch, :put], as: :update_jobseeker_profile

  get 'jobseeker/create', to: 'jobseekers#new', as: :create_new_jobseeker
  get 'jobseeker/recommendations', to: 'jobseekers#recommendations', as: :recommendations
  get 'jobseeker/recommendations/consolidated', to: 'jobseekers#consolidated_recommendations', as: :consolidated_recommendations

  get '/search', to: 'pages#search', as: :search

  resources :users
  resources :admins, controller: 'users'
  resources :employers
  resources :jobseekers

  root 'pages#home'

end

app/models/jobseeker.rb
class Jobseeker < User
  has_many :jobapplications, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,      :presence => true,
            :length => { :maximum => 50 }
  validates :username,  :presence => true,
            :length => { :maximum => 15 },
            :uniqueness => { :case_sensitive => false}
  validates :password,  :presence => true,
            confirmation: true,
            :length => { :within => (5..20) },
            :if => :password
  validates :email, presence: true, length: { maximum: 60}, format: { with: VALID_EMAIL_REGEX }


  before_save :encrypt_password, :if => :password

end

app/controllers/jobseekers_controller.rb
class JobseekersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:new, :create]
  before_action :check_if_jobseeker, except: [:new, :create]
  before_action :jobapp_check_for_id_application, only: [:view_application]


  # GET /users
  # GET /users.json
  def index
    @jobs = Job.all
    @this_user = Jobseeker.find(session[:user_id])
    @category = Category.all
    @tags = Tag.all
    @employer = Employer.all
    @titles_true = @desc_true = @emp_true = @cat_true = @tags_true = true
    @jobapplications = Jobapplication.where(jobseeker_id: session[:user_id])
  end

  def view_applications
    @jobs = Job.all
    @jobapplications = Jobapplication.where(jobseeker_id: session[:user_id])
  end

  def view_application
    @application = Jobapplication.find(params[:id])
    @job = Job.find(@application.job_id)
    @employer = Employer.find(@job.employer_id)
  end

  # GET /users/1
  # GET /users/1.json
  def show

  end

  def view_job
    @job = Job.find(params[:id])
    @category = Category.find(@job.category_id).name
    @employer = Employer.find(@job.employer_id).name
    tags_list = Tag.where(job_id: @job.id)
    @tags = ""
    tags_list.each do |tag|
      @tags += " " + tag.name.strip
    end
    @applied = Jobapplication.find_by job_id: @job.id, jobseeker_id: session[:user_id]
  end
  # GET /users/new
  def new
    @user = Jobseeker.new
  end

  def apply_job
    @application = Jobapplication.new
    @job = Job.find(params[:id])
    @user = Jobseeker.find(session[:user_id])
    @employer_name = Employer.find(@job.employer_id).name
    @date = Date.today
    @status = "Pending"
  end
  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = Jobseeker.new(user_params)
    if(@user.username == "super")
      @user = Admin.new(user_params)
      @user.username = "super"
      @user.password = "super"
      @user.password_confirmation = "super"
      @user.name = "Super Admin"
      respond_to do |format|
        if @user.save
          format.html { redirect_to pages_home_path, notice: 'New Super Admin account created!' }
          format.json { render :show, status: :created, location: jobseeker_home_path }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @user.save
          format.html { redirect_to pages_home_path, notice: 'New JobSeeker account created!' }
          format.json { render :show, status: :created, location: jobseeker_home_path }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def create_application
    @jobapplication = Jobapplication.new(application_params)
    @job = Job.find(params[:jobapplication][:job_id])
    @user = Employer.find(@job.employer_id)

    if(Jobapplication.find_by job_id: @job.id, jobseeker_id: session[:user_id])
      redirect_home
    else
      respond_to do |format|
        if @jobapplication.save
          UserMailer.new_job_application(@user,@job).deliver

          format.html { redirect_to jobseeker_home_path, notice: 'Job application submitted!' }
          format.json { render :show, status: :created, location: jobseeker_home_path }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def newemp2
    @user = JobSeeker.new
  end

  def createemp2
    @user = JobSeeker.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def view_jobseeker_profile
    @title = 'My Profile'
    @jobseeker = Jobseeker.find(session[:user_id])
  end

  def edit_jobseeker_profile
    @title = 'Edit Profile'
    @jobseeker = Jobseeker.find(session[:user_id])
  end

  def update_jobseeker_profile
    @user = Jobseeker.find(session[:user_id])
    respond_to do |format|
      if @user.update(jobseeker_update_params)
        format.html { redirect_to jobseeker_profile_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit_jobseeker_profile }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_jobseeker_pass
    @title = 'Change Password'
    @user = User.find(session[:user_id])
  end

  def update_jobseeker_password
    @user = Jobseeker.find(session[:user_id])
    respond_to do |format|
      if @user.update(jobseeker_password_params)
        format.html { redirect_to jobseeker_profile_path, notice: 'Password was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :new_jobseeker_pass }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def recommendations
    @jobs, @jobs_cat, @jobs_emp = Job.recommendations(session[:user_id])
    @category = Category.all
    @tags = Tag.all
    @employer = Employer.all
    @jobapplications = Jobapplication.where(jobseeker_id: session[:user_id])
  end

  def consolidated_recommendations
    @jobs, jobs_cat, jobs_emp = Job.recommendations(session[:user_id])
    #@jobs.concat(jobs_cat.concat(jobs_emp))
    #@jobs.merge(jobs_cat.merge(jobs_emp))
    @jobs = jobs_cat | jobs_emp | @jobs
    @category = Category.all
    @tags = Tag.all
    @employer = Employer.all
    @jobapplications = Jobapplication.where(jobseeker_id: session[:user_id])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    jobapp_check_for_id_jobseeker
    @user = Jobseeker.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:jobseeker).permit(:name, :email, :username, :password_hash, :password_salt, :password, :password_confirmation, :phone, :type, :skills, :resume)
  end

  def application_params
    params.require(:jobapplication).permit(:job_id, :jobseeker_id, :application_date, :cover_letter, :status)
  end

  def jobseeker_update_params
    params.require(:jobseeker).permit(:name, :email, :username, :phone, :type, :skills, :resume)
  end

  def jobseeker_password_params
    params.require(:jobseeker).permit(:password_hash, :password_salt, :password, :password_confirmation, :type)
  end

end

app/views/jobseekers/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :skills, "Your Skills" %><br>
      <%= f.text_area :skills %>
    </div>
    <div class="field">
      <%= f.label :resume, "Resume" %><br>
      <%= f.text_area :resume %>
    </div>
    <div class="actions">
      <%= f.submit "Create Account" %>
    </div>
<% end %>

app/views/jobseekers/_jobs_table.html.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Employer</th>
    <th>Category</th>
    <th>Deadline</th>
    <th>Tags</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @jobs.each do |job| %>
    <% skip = 0 %>
    <% if @jobapplications %>
      <% if @jobapplications.find_by job_id: job.id %>
        <% skip = 1 %>
      <% end %>
    <% end %>
    <% unless skip == 1 %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= @employer.find(job.employer_id).name %></td>
        <td><%= @category.find(job.category_id).name %></td>
        <td><%= job.deadline %></td>
        <td>
          <% tag_list = @tags.where(job_id: job.id) %>
          <% job.id %>
          <% if tag_list %>
              <% tag_list.each do |tag|%>
                  <%= tag.name %>
              <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', view_job_path(job) %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/jobseekers/apply_job.html.erb
<h1>Apply to job:</h1>

<%= form_for(@application) do |f| %>
    <% if @application.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

          <ul>
            <% @application.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <strong>Title:</strong>
      <%= @job.title %>
    </p>

    <p>
      <strong>Employer:</strong>
      <%= @employer_name %>
    </p>

    <div class="field">
      <%= f.label :cover_letter, "Cover Letter (Optional)" %><br>
      <%= f.text_area :cover_letter %>
    </div>
    <%= f.hidden_field :job_id, value: @job.id %>
    <%= f.hidden_field :jobseeker_id, value: @user.id %>
    <%= f.hidden_field :application_date, value: @date %>
    <%= f.hidden_field :status, value: @status %>
    <div class="actions">
      <%= f.submit "Apply" %>
    </div>
<% end %>

<%= link_to 'Back', jobs_path %>

app/views/jobseekers/consolidated_recommendations.html.erb
<h2>Recommended Jobs for you (based on your application history):</h2>

<%= link_to 'View recommendations by area', recommendations_path %><br>

<%= render 'jobs_table' %><br>


<br>
<%= link_to 'Back to home', jobseeker_home_path %><br>

app/views/jobseekers/edit_jobseeker_profile.html.erb
<h1>Editing profile</h1>

<%= form_for(@jobseeker, as: :jobseeker, url: update_jobseeker_profile_path) do |f| %>
    <% if @jobseeker.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@jobseeker.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @jobseeker.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :skills %><br>
      <%= f.text_field :skills %>
    </div>
    <div class="field">
      <%= f.label :resume %><br>
      <%= f.text_area :resume %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<br><%= link_to 'Change Password', new_jobseeker_pass_path %><br>
<%= link_to 'Back', jobseeker_profile_path %>

app/views/jobseekers/index.html.erb
<h1>Hello, <%= @this_user.name.titleize %>!</h1>
<h2>Available Jobs:</h2>

<%= render 'pages/search_form' %>

<%= render 'jobs_table' %>

<br>


<br>
<%= link_to 'My Applications', view_applications_path %>&nbsp;|
<%= link_to 'My Profile', jobseeker_profile_path %>&nbsp;|
<%= link_to 'DireWolf Recommends', recommendations_path %><br>
<%= link_to 'Log out', log_out_path %>

app/views/jobseekers/new.html.erb
<h1>New Job-seeker Account</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_home_path %>

app/views/jobseekers/new_jobseeker_pass.html.erb
<h1>Change Password</h1>

<%= form_for(@user, as: :jobseeker, url: update_jobseeker_password_path) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :password, "Enter new password" %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirm password" %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<br>
<%= link_to 'Back', edit_jobseeker_profile_path %>

app/views/jobseekers/recommendations.html.erb
<h2>Recommended Jobs for you (based on your application history):</h2>

<%= link_to 'View consolidated recommendations', consolidated_recommendations_path %><br>

<h3>Recommendations by Tags:</h3>
<%= render 'jobs_table' %><br>

<% @jobs = @jobs_cat %>
<h3>Recommendations by Categories:</h3>
<%= render 'jobs_table' %><br>

<% @jobs = @jobs_emp %>
<h3>Recommendations by Employers:</h3>
<%= render 'jobs_table' %>

<br>


<br>
<%= link_to 'Back to home', jobseeker_home_path %><br>

app/views/jobseekers/view_application.html.erb
<p>
  <strong>Employer:</strong>
  <%= @employer.name %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Job description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Cover letter:</strong>
  <%= @application.cover_letter %>
</p>

<p>
  <strong>Application date:</strong>
  <%= @application.application_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @application.status %>
</p>

<%= link_to 'Back', view_applications_path %>

app/views/jobseekers/view_applications.html.erb
<h2>Your Job applications:</h2>

<table>
  <thead>
  <tr>
    <th>Job title</th>
    <th>Application date</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @jobapplications.each do |jobapplication| %>
      <tr>
        <td><%= @jobs.find(jobapplication.job_id).title %></td>
        <td><%= jobapplication.application_date %></td>
        <td><%= jobapplication.status %></td>
        <td><%= link_to 'Show', view_application_path(jobapplication) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>


<br>
<%= link_to 'Back', jobseeker_home_path %>&nbsp;

app/views/jobseekers/view_job.html.erb
<p id="notice"><%= notice %></p>

<%= render "jobs/show_job" %>
<% unless @applied %>
    <%= link_to 'Apply', apply_job_path(@job) %> |
<% end %>
<%= link_to 'Back', jobseeker_home_path %>

app/views/jobseekers/view_jobseeker_profile.html.erb
<h1>My Profile</h1>

<p>
  <strong>Name:</strong>
  <%= @jobseeker.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @jobseeker.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @jobseeker.username %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @jobseeker.phone %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @jobseeker.skills %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @jobseeker.resume %>
</p>


<%= link_to 'Edit', edit_jobseeker_profile_path %> |
<%= link_to 'Back', jobseeker_home_path %>